apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: node-taint-chaos
  namespace: default
spec:
  # It can be true/false
  annotationCheck: 'true'
  # It can be active/stop
  engineState: 'active'
  #ex. values: ns1:name=percona,ns2:run=nginx 
  appinfo:
      appns: 'default'
      applabel: 'app=frontend'
      appkind: 'deployment'
  chaosServiceAccount: node-taint-sa
  # It can be delete/retain
  jobCleanUpPolicy: 'delete'
  experiments:
    - name: node-taint
      spec:
        components:
        # nodeSelector: 
        #   # provide the node labels
        #   kubernetes.io/hostname: 'node02'        
          env:
            # set target node name
            - name: TARGET_NODE
              value: 'gke-tfg-graphics-default-pool-68de6796-c8bw'
              
             # set taint label & effect
             # key=value:effect or key:effect
            - name: TAINTS
              value: 'node.kubernetes.io/unreachable:NoExecute'
