apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: node-ram-chaos
  namespace: default
spec:
  # It can be true/false
  annotationCheck: 'true'
  # It can be active/stop
  engineState: 'active'
  #ex. values: ns1:name=percona,ns2:run=nginx 
  appinfo:
      appns: 'default'
      applabel: 'app=frontend'
      appkind: 'deployment'
  chaosServiceAccount: node-memory-hog-sa
  # It can be delete/retain
  jobCleanUpPolicy: 'delete'
  experiments:
    - name: node-memory-hog
      spec:
        components:
          env:
            # set chaos duration (in sec) as desired
            - name: TOTAL_CHAOS_DURATION
              value: '120'

            ## Specify the size as percent of total node capacity Ex: '30'
            ## Note: For consuming memory in mebibytes change the variable to MEMORY_CONSUMPTION_MEBIBYTES
            - name: MEMORY_CONSUMPTION_MEBIBYTES
              value: '2046'
            
            # ENTER THE COMMA SEPARATED TARGET NODES NAME
            - name: TARGET_NODES
              value: 'gke-tfg-graphics-default-pool-68de6796-c8bw''
