apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: kubelet-kill
  namespace: default
spec:
    appinfo:
      appns: 'default'
      applabel: 'app=frontend'
      appkind: 'deployment'
  # It can be true/false
    annotationCheck: 'true'
  # It can be active/stop
    engineState: 'active'
    chaosServiceAccount: kubelet-service-kill-sa
  # It can be delete/retain
    jobCleanUpPolicy: 'delete'
    experiments:
      - name: kubelet-service-kill
        spec:
          components:
            nodeSelector: 
          #   # provide the node labels
                kubernetes.io/hostname: 'gke-tfg-graphics-default-pool-68de6796-c8bw'    
            env:
              - name: TOTAL_CHAOS_DURATION
                value: '90' # in seconds
                
              # provide the target node name
              - name: TARGET_NODE
                value: 'gke-tfg-graphics-default-pool-68de6796-c8bw'
