apiVersion: litmuschaos.io/v1alpha1
kind: ChaosSchedule
metadata:
  name: schedule-container-kill
spec:
  schedule:
    now: true
  auxiliaryAppInfo: 'istio.io/rev=default'
  engineTemplateSpec:
    appinfo:
      appns: 'default'
      applabel: 'app=paymentservice'
      appkind: 'deployment'
    annotationCheck: 'true'
    engineState: 'active'
    chaosServiceAccount: container-kill-sa
    monitoring: false
  # It can be delete/retain
  jobCleanUpPolicy: 'delete' 
  experiments:
    - name: container-kill
      spec:
        components:
          env:
            # provide the chaos interval
            - name: CHAOS_INTERVAL
              value: '10'

            # provide the total chaos duration
            - name: TOTAL_CHAOS_DURATION
              value: '20'

            # provide the name of container runtime
            # for litmus LIB, it supports docker, containerd, crio
            # for pumba LIB, it supports docker only
            - name: CONTAINER_RUNTIME
              value: 'docker'

            # provide the socket file path
            - name: SOCKET_PATH
              value: '/var/run/docker.sock'

