apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: schedule-docker-kill
  namespace: default
spec: 
  # It can be delete/retain
  jobCleanUpPolicy: 'delete'
  # It can be true/false
  annotationCheck: 'true'
  # It can be active/stop
  engineState: 'active'
  appinfo: 
    appns: 'default'
    # FYI, To see app label, apply kubectl get pods --show-labels
    applabel: 'app=frontend'
    appkind: 'deployment'
  chaosServiceAccount: pod-network-latency-sa
 experiments:
    - name: docker-service-kill
      spec:
        components:
        # nodeSelector: 
        #   # provide the node labels
        #   kubernetes.io/hostname: 'node02'
          env:
            # set chaos duration (in sec) as desired
            - name: TOTAL_CHAOS_DURATION
              value: '90'

             # provide the actual name of node under test
            - name: APP_NODE
              value: 'node-01'
