apiVersion: litmuschaos.io/v1alpha1
kind: ChaosSchedule
metadata:
  name: schedule-docker-kill
spec:
  schedule:
    now: true
  engineTemplateSpec:
    appinfo:
      appns: 'default'
      applabel: 'app=frontend'
      appkind: 'deployment'
    annotationCheck: 'true'
    engineState: 'active'
    chaosServiceAccount: docker-service-kill-sa
    monitoring: false
    jobCleanUpPolicy: 'delete'
    experiments:
    - name: docker-service-kill
      spec:
        components:
        # nodeSelector: 
        #   # provide the node labels
        #   kubernetes.io/hostname: 'node02'
          env:
            # set chaos duration (in sec) as desired
            - name: TOTAL_CHAOS_DURATION
              value: '90'

             # provide the actual name of node under test
            - name: APP_NODE
              value: 'node-01'
