  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-escenario-ram
  namespace: dev
  labels:
    app: stress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      labels:
        app: stress
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          limits:
            memory: "200Mi"
          requests:
            memory: "100Mi"
