apiVersion: v1
kind: Namespace
metadata:
  name: chaos-test
  labels:
     name: chaos-testing-label
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-chaos-testing
  namespace: chaos-test
  labels:
    app: test-label
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-label
  template:
    metadata:
      labels:
        app: test-label
    spec:
      containers:
      - name: nginx
        image: nginx
